[ClassVersion("1.1.0"),FriendlyName("OctopusServer")] 
class OctopusServer : OMI_BaseResource
{
	[key] string Name;
    [write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
	[write] string DatabaseEndpoint;
	[write] string DatabaseName;
	[write] string DatabaseUserName;
	[write] string DatabasePassword;
	[write] string FileShareLocation;
	[write] string HostName;
	[write] string LocalIpAddress;
	[write] string LocalHostName;
	[write] string MasterKey;
	[write] string AdminPassword;
	[write] string LicenceBase64;
	[write] string Version;
};